stages:
    - deploy

deploy:
    image: ubuntu:latest
    stage: deploy
    only:
        - main
    before_script:
        - apt-get -yq update
        - apt-get -yqq install ssh
        - install -m 600 -D /dev/null ~/.ssh/id_ed25519
        - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - mkdir -p ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    script:
        - scp -r -i ~/.ssh/id_ed25519 build/web/* $SSH_USER@$SSH_HOST:WORK_DIR
        - ssh -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST "chmod -R 777 $WORK_DIR"
    after_script:
        - rm -rf ~/.ssh
