name: boyshub
description: Find hangout places, playstations, and more in one app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  permission_handler: ^10.4.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.8.7
  file_picker: ^10.1.9
  flutter_js: ^0.8.3
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.8
  flutter_dotenv: ^5.0.2
  webview_flutter: ^4.13.0
  flutter_map: ^8.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - .env

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
flutter_icons:
  android: true
#  ios: true
  image_path: "assets/icons/app_icon.jpg"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/app_icon.jpg
  android: true
#  ios: true